config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :course_types
  resources :cuisine_categories
  resources :regions
  resources :ingredients

  root 'application#homepage'

  match 'create_new' => 'application#create_new', :via => [:get]
  match 'homepage' => 'application#homepage', :via => [:get]
  match 'admin' => 'application#admin', :via => [:get]
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  include RecipeHelper

  has_many :recipe_cuisines
  has_many :cuisine_categories, :through => :recipe_cuisines
  has_many :steps
  has_many :recipe_ingredient_amounts
  has_many :ingredient_amounts, :through => :recipe_ingredient_amounts
  has_many :recipe_courses
  has_many :course_types, :through => :recipe_courses
  has_many :ingredients, :through => :ingredient_amounts

  validates :cuisine_categories, :presence => true
  validates :course_types, :presence => true
  validates :name, :presence => true
  validates :prep_time, :presence => true, :numericality =>  {:greater_than_or_equal_to => 0}
  validates :cook_time, :presence => true, :numericality =>  {:greater_than_or_equal_to => 0}

  accepts_nested_attributes_for :steps, :reject_if => :all_blank
  accepts_nested_attributes_for :ingredient_amounts, :reject_if => :all_blank
  accepts_nested_attributes_for :ingredients

  DIFFICULTIES = [
    ["Easy", 1],
    ["Medium", 2],
    ["Advanced", 3],
    ["Expert", 4]
  ]

  def self.six_random_recipes
    max = Recipe.count
    recipes = []
  
    6.times do
      recipes << Recipe.all[rand(max)]
    end

    recipes
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :load_recipe, :only => [:show, :edit, :update]

  def index
    @recipe_search = RecipeSearch.new() 

    unless params[:recipe_search].nil?
      service = RecipeSearchService.new(:params => params[:recipe_search])
      service.execute

      if service.successful?
        @recipes = service.recipes
      end
    end
  end

  def show
  end

  def new
    @recipe = Recipe.new()
  end

  def create
    params[:recipe][:course_types] = CourseType.where(:id => params[:recipe][:course_types].map { |ct| ct.to_i })
    params[:recipe][:cuisine_categories] = CuisineCategory.where(:id => params[:recipe][:cuisine_categories].map { |cc| cc.to_i })

    @recipe = Recipe.new(params[:recipe].to_unsafe_hash)
    if @recipe.valid?
      @recipe.save!

      @recipe.steps.each do |step|
        unless step.step_text.empty?
          step.save!
        else
          step.destroy!
        end
      end

      @recipe.ingredient_amounts do |ia|
        ap "///////////////////////////////////////////////////////"
        ap "Ingredient!!!!!!!!!"
        ap "///////////////////////////////////////////////////////"
        ap ia
        ap ia.ingredient
        unless ia.ingredient.name.empty?
          ia.save!
        else
          ia.destroy!
        end
      end

      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    params[:recipe][:course_types] = map_course_types
    params[:recipe][:cuisine_categories] = map_cuisine_categories
    
    @recipe.update_attributes(params[:recipe].to_unsafe_hash)

    ap @recipe
    ap @recipe.ingredient_amounts.count
    ap @recipe.ingredient_amounts.map { |ia| ia.ingredient }
    ap @recipe.ingredient_amounts.map { |ia| ia.ingredient.name.empty? }

    ActiveRecord::Base.transaction do
      @recipe.steps.each do |step|
        unless step.step_text.empty?
          step.save!
        else
          step.destroy!
        end
      end
    end

    ActiveRecord::Base.transaction do
      @recipe.ingredient_amounts.to_a.each do |ia|
        if ia.ingredient.name.empty?
          ia.destroy! 
        else
          ia.save!
        end
      end
    end

    redirect_to recipe_path(@recipe)
  end

  private

  def load_recipe
    @recipe = Recipe.find(params[:id])
  end

  def map_course_types
    CourseType.where(:id => params[:recipe][:course_types].map { |ct| ct.to_i })
  end

  def map_cuisine_categories
    CuisineCategory.where(:id => params[:recipe][:cuisine_categories].map { |cc| cc.to_i })
  end
end

app/helpers/recipe_helper.rb
module RecipeHelper

  def setup_recipe(recipe)

    10.times { recipe.steps.build }

    10.times do
      ingredient_amount = IngredientAmount.new
      ingredient_amount.ingredient = Ingredient.new 
      ingredient_amount.amount = Amount.new 
      recipe.ingredient_amounts << ingredient_amount
    end

    recipe
  end

end

app/views/recipes/_form.html.haml
.container
  .row-fluid
    .col-xs-12
      .row
        .col-xs-12
          .panel.panel-default
            .panel-heading New Recipe
            .panel-body
              .panel-body
                =simple_form_for setup_recipe(@recipe) do |f|
                  .row
                    .col-sm-6.col.xs-12
                      .form-group 
                        .col-xs-4
                          =f.label :name
                        .col-xs-8
                          =f.input_field :name, :class => 'form-control'
                          .text-error
                            =f.error :name
                    .col-sm-6.col.xs-12
                      .form-group 
                        .col-xs-4
                          =f.label :difficulty
                        .col-xs-8
                          =f.select :difficulty, Recipe::DIFFICULTIES, :class => 'form-control'
                          .text-error
                            =f.error :difficulty
                  .row
                    .col-sm-6.col.xs-12 
                      .form-group 
                        .col-xs-4
                          =f.label :prep_time, "Prep Time (mins):"
                        .col-xs-8
                          =f.input_field :prep_time, :class => 'form-control', :min => 0
                          .text-error
                            =f.error :prep_time
                    .col-sm-6.col.xs-12 
                      .form-group 
                        .col-xs-4
                          =f.label :cook_time, "Cook Time (mins):"
                        .col-xs-8
                          =f.input_field :cook_time, :class => 'form-control', :min => 0
                          .text-error
                            =f.error :cook_time
                  .row
                    .col-sm-6.col.xs-12 
                      .form-group 
                        .col-xs-4
                          =f.label :cuisine_categories
                        .col-xs-8
                          =f.collection_select :cuisine_categories, CuisineCategory.all, :id, :name, {}, {:allow_blank => false, :multiple => true, :class => 'form-control'}
                          .text-error
                            =f.error :cuisine_categories
                    .col-sm-6.col.xs-12 
                      .form-group 
                        .col-xs-4
                          =f.label :course_types
                        .col-xs-8
                          =f.collection_select :course_types, CourseType.all, :id, :name, {}, {:multiple => true, :class => 'form-control'}
                          .text-error
                            =f.error :course_types
                  .row 
                    %strong Ingredients
                  .row
                    .col-xs-12
                      .col-xs-3
                        %center Qnty.
                      .col-xs-3
                        %center Measurement
                      .col-xs-6
                        %center Ingredient
                  = f.simple_fields_for :ingredient_amounts do |ia|
                    .row 
                      .col-xs-12
                        .form-group
                          = ia.simple_fields_for :amount do |amt|
                            .col-xs-3
                              = amt.input_field :quantity, :class => 'form-control', :min => 0
                            .col-xs-3
                              = amt.select :measurement, Amount::MEASUREMENTS, :class => 'form-control'
                          = ia.simple_fields_for :ingredient do |ing|
                            .col-xs-6
                              = ing.input_field :name, :class => 'form-control'
                  .row 
                    %strong Steps
                  -step_num = 1
                  = f.simple_fields_for :steps do |s|
                    .row
                      .col-xs-12
                        .form-group  
                          .col-xs-2
                            =s.label :step_text, "Step #{step_num}:"
                          .col-xs-10
                            =s.input_field :step_text, :class => 'form-control'
                    -step_num += 1
                  .row
                    %center
                      -if @new
                        =f.submit "Create Recipe"
                      -else
                        =f.submit "Save Recipe"

app/views/recipes/edit.html.haml
- @show = false
= render :partial => "form"

app/views/recipes/index.html.haml
.container
  .row-fluid
    .col-xs-12
      .row
        .col-xs-12
          .panel.panel-default
            .panel-heading Recipe Search
            .panel-body
              =simple_form_for @recipe_search, :method => :get, :url => recipes_path do |f|
                .row
                  .col-sm-6.col.xs-12 
                    .col-xs-4
                      =f.label :name
                    .col-xs-8
                      =f.input_field :name 
                  .col-sm-6.col.xs-12 
                    .col-xs-4
                      =f.label :course
                    .col-xs-8
                      =f.select :course, CourseType.all.map {|ct| [ct.name, ct.id]}, :include_blank => true
                .row
                  .col-sm-6.col.xs-12
                    .col-xs-4
                      =f.label :max_time
                    .col-xs-8
                      =f.input_field :max_time 
                  .col-sm-6.col.xs-12
                    .col-xs-4
                      =f.label :cuisine_category
                    .col-xs-8
                      =f.select :cuisine_category, CuisineCategory.all.map {|cc| [cc.name, cc.id]}, :include_blank => true
                .row
                  .col-xs-12
                    %center
                      =f.submit "Find", :class => 'btn btn-sm btn-default'
      -unless @recipes.nil?
        .row 
          .col-xs-12
            .panel.panel-default
              .panel-heading Recipes
              .panel-body
                -@recipes.each do |recipe|
                  .col-xs-6
                    .panel.panel-default
                      .panel-heading= link_to recipe.name, recipe_path(recipe)
                      .panel-body
                        .row
                          .col-sm-6.col-xs-12
                            .row
                              .col-xs-5 
                                %strong Prep Time
                              .col-xs-7
                                = "#{recipe.prep_time.to_i} minutes"
                          .col-sm-6.col-xs-12
                            .row
                              .col-xs-5 
                                %strong Cook Time
                              .col-xs-7
                                = "#{recipe.cook_time.to_i} minutes"
                        %br
                        .row
                          .col-sm-6.col-xs-12
                            .row
                              .col-xs-5 
                                %strong Cuisine Type(s)
                              .col-xs-7
                                = recipe.cuisine_categories.map { |cc| cc.name}.join(', ')
                          .col-sm-6.col-xs-12
                            .row
                              .col-xs-5 
                                %strong Course
                              .col-xs-7
                                =recipe.course_types.map { |ct| ct.name }.join(', ')

app/views/recipes/new.html.haml
- @new = true
= render :partial => "form"

app/views/recipes/show.html.haml
.container
  .row-fluid
    .col-xs-12
      .row
        .col-xs-12
          .panel.panel-default
            .panel-heading.ro
              .col-xs-6
                = @recipe.name
              .col-xs-6
                .pull-right
                  = button_to "Edit", edit_recipe_path(@recipe), :method => :get, :class => 'btn btn-default btn-xs'
            .panel-body
              .row
                .col-sm-6.col-xs-12
                  .row
                    .col-xs-5 
                      %strong Prep Time
                    .col-xs-7
                      = "#{@recipe.prep_time.to_i} minutes"
                .col-sm-6.col-xs-12
                  .row
                    .col-xs-5 
                      %strong Cook Time
                    .col-xs-7
                      = "#{@recipe.cook_time.to_i} minutes"
              %br
              .row
                .col-sm-6.col-xs-12
                  .row
                    .col-xs-5 
                      %strong Cuisine Type(s)
                    .col-xs-7
                      = @recipe.cuisine_categories.map { |cc| cc.name }.join(', ')
                .col-sm-6.col-xs-12
                  .row
                    .col-xs-5 
                      %strong Course
                    .col-xs-7
                      = @recipe.course_types.map { |ct| ct.name }.join(', ')
              %br
              - @recipe.ingredient_amounts.each do |ia|
                .row
                  .col-xs-6= "#{ia.amount.fraction_quantity} #{Amount::MEASUREMENTS[ia.amount.measurement.to_i].first} #{ia.ingredient.name}"
              %br
              -@recipe.steps.each do |step|
                .row
                  .col-xs-1 
                    %strong Step: 
                  .col-xs-11
                    = step.step_text
                %br 