config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :course_types
  resources :cuisine_categories
  resources :regions
  resources :ingredients

  root 'application#homepage'

  match 'create_new' => 'application#create_new', :via => [:get]
  match 'homepage' => 'application#homepage', :via => [:get]
  match 'admin' => 'application#admin', :via => [:get]
end

app/views/shared/admin.html.haml
.container
  .row-fluid
    .col-xs-12
      .row
        .col-xs-12
          .row
            .col-md-4.col-sm-6.col-xs-12
              %a.nav-link.fa-nav-link{:href => "#{course_types_path}"}
                .panel.panel-default
                  .panel-body
                    .row
                      .col-xs-12
                        %center
                          %i.fa.fa-cutlery.fa-5x
                      .col-xs-12
                        %center
                          ="Edit Courses"
            .col-md-4.col-sm-6.col-xs-12
              %a.nav-link.fa-nav-link{:href => "#{cuisine_categories_path}"}
                .panel.panel-default
                  .panel-body
                    .row
                      .col-xs-12
                        %center
                          %i.fa.fa-flag.fa-5x
                      .col-xs-12
                        %center
                          ="Edit Cuisine Categories"
            .col-md-4.col-sm-6.col-xs-12
              %a.nav-link.fa-nav-link{:href => "#{regions_path}"}
                .panel.panel-default
                  .panel-body
                    .row
                      .col-xs-12
                        %center
                          %i.fa.fa-globe.fa-5x
                      .col-xs-12
                        %center
                          ="Edit Regions"
            .col-md-4.col-sm-6.col-xs-12
              %a.nav-link.fa-nav-link{:href => "#{ingredients_path}"}
                .panel.panel-default
                  .panel-body
                    .row
                      .col-xs-12
                        %center
                          %i.fa.fa-flask.fa-5x
                      .col-xs-12
                        %center
                          ="Edit Ingredients" 

app/views/shared/create_new.html.haml
.container
  .row-fluid
    .col-xs-12
      .row
        .col-xs-12
          .row
            .col-md-4.col-sm-6.col-xs-12
              %a.nav-link.fa-nav-link{:href => "#{new_recipe_path}"}
                .panel.panel-default
                  .panel-body
                    .row
                      .col-xs-12
                        %center
                          %i.fa.fa-file-text-o.fa-5x
                      .col-xs-12
                        %center
                          ="Create New Recipe"
            .col-md-4.col-sm-6.col-xs-12
              %a.nav-link.fa-nav-link{:href => "#{new_course_type_path}"}
                .panel.panel-default
                  .panel-body
                    .row
                      .col-xs-12
                        %center
                          %i.fa.fa-cutlery.fa-5x
                      .col-xs-12
                        %center
                          ="Create New Course"
            .col-md-4.col-sm-6.col-xs-12
              %a.nav-link.fa-nav-link{:href => "#{new_cuisine_category_path}"}
                .panel.panel-default
                  .panel-body
                    .row
                      .col-xs-12
                        %center
                          %i.fa.fa-flag.fa-5x
                      .col-xs-12
                        %center
                          ="Create New Cuisine Category"
            .col-md-4.col-sm-6.col-xs-12
              %a.nav-link.fa-nav-link{:href => "#{new_region_path}"}
                .panel.panel-default
                  .panel-body
                    .row
                      .col-xs-12
                        %center
                          %i.fa.fa-globe.fa-5x
                      .col-xs-12
                        %center
                          ="Create New Region"
            .col-md-4.col-sm-6.col-xs-12
              %a.nav-link.fa-nav-link{:href => "#{new_ingredient_path}"}
                .panel.panel-default
                  .panel-body
                    .row
                      .col-xs-12
                        %center
                          %i.fa.fa-flask.fa-5x
                      .col-xs-12
                        %center
                          ="Create New Ingredient" 

app/views/shared/homepage.html.haml
.container
  .row-fluid
    .col-xs-12
      .row
        - Recipe.six_random_recipes.each do |recipe|
          .col-xs-6
            .panel.panel-default
              .panel-heading= link_to recipe.name, recipe_path(recipe)
              .panel-body
                .row
                  .col-sm-6.col-xs-12
                    .row
                      .col-xs-5 
                        %strong Prep Time
                      .col-xs-7
                        = "#{recipe.prep_time.to_i} minutes"
                  .col-sm-6.col-xs-12
                    .row
                      .col-xs-5 
                        %strong Cook Time
                      .col-xs-7
                        = "#{recipe.cook_time.to_i} minutes"
                %br
                .row
                  .col-sm-6.col-xs-12
                    .row
                      .col-xs-5 
                        %strong Cuisine Type(s)
                      .col-xs-7
                        = recipe.cuisine_categories.map { |cc| cc.name}.join(', ')
                  .col-sm-6.col-xs-12
                    .row
                      .col-xs-5 
                        %strong Course
                      .col-xs-7
                        = recipe.course_types.map { |ct| ct.name}.join(', ')